services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=ordersApp
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Orders
    ports:
      - '5482:5432'
    volumes:
      - ./docker/database:/docker-entrypoint-initdb.d
  
  app:
    build: 
      dockerfile: dockerfile
      context: ./
    ports:
      - "3333:3333"
    environment:
      - HOST='0.0.0.0'
      - PORT=3333
      - BROKER_URL=''